<?php

/**
 * @file
 * Contains di_paragraphs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function di_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the di_paragraphs module.
    case 'help.page.di_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paragraphs and shared fields') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function di_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'field__entity_reference_revisions' => [
      'base hook' => 'paragraph',
    ],
    // 'field__paragraph__field_media__media' => [
    //   'base hook' => 'paragraph',
    // ],
    // 'paragraph__media' => [
    //   'base hook' => 'paragraph',
    // ],
    // 'paragraph__section' => [
    //   'base hook' => 'paragraph',
    // ],
    // 'paragraph__text' => [
    //   'base hook' => 'paragraph',
    // ],
  ];
}
